; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_wrover]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -O3 ; Activates maximum optimization for fast math execution loops


; This is the library call for the esp32-cam
; Instead of downloading it locally, we call the fill from github to get the latest version
lib_deps =
    https://github.com/eloquentarduino/EloquentEsp32cam.git